server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name front.local.prefpet.com.br;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name front.local.prefpet.com.br;

    ssl_certificate /etc/nginx/certs/fullchain.crt;
    ssl_certificate_key /etc/nginx/certs/wildcard.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /dev/stdout;
    error_log /dev/stderr warn;
}